"""SB1–SB3 StudyDraft compiler façade — emit / hydrate / session ser-de.

C-24 (QI-07-07) splits hydrate/emit helpers and widget helpers into sibling
modules. Public names stay here. Pure helper: no Streamlit, no execute /
launch / preview. Pages import this module directly. ``emit_study_spec`` is
the only path into ``validate_study_spec``.
"""

from __future__ import annotations

from typing import Any

from thesistester.data import loader as _data_loader
from thesistester.study.builder_draft import (
    COMMON_MA_LENGTHS,
    DEFAULT_FORMAT_PROFILE,
    DEFAULT_NEW_DRAFT_DATASET_PATH,
    DEFAULT_NEW_DRAFT_FORMAT_PROFILE,
    DEFAULT_NEW_DRAFT_INSTRUMENT,
    DEFAULT_NEW_DRAFT_SOURCE_TIMEZONE,
    DIRECTION_MODE_CONSTANT,
    DIRECTION_MODE_FACTOR,
    DIRECTION_MODE_OPTIONS,
    MULTIPLE_TESTING_OPTIONS,
    OTF_PRESETS,
    OTF_PRESET_LABELS,
    INGESTION_MODE_PRIMARY,
    OTF_PRESET_ORDER,
    PREFERRED_REPORT_GROUP_BY,
    PRIMARY_METRIC_OPTIONS,
    STAGE_MODE_EXPLICIT,
    STAGE_MODE_FILTER,
    STAGE_MODE_FULL,
    STAGE_MODE_OPTIONS,
    STUDIES_BUILDER_DRAFT_KEY,
    STUDIES_BUILDER_PENDING_SYNC_KEY,
    StudyDraft,
    TF_MODE_EXPLICIT,
    TF_MODE_NO_MA,
    TF_MODE_OPTIONS,
    TF_MODE_PRODUCT_DEFAULT,
    WIDGET_KEY_BATTERY_GRID,
    WIDGET_KEY_BATTERY_VALIDATION,
    WIDGET_KEY_BATTERY_WALK_FORWARD,
    WIDGET_KEY_COMMISSION,
    WIDGET_KEY_CONFIRM_ABOVE_RUNS,
    WIDGET_KEY_CONFLUENCE_ANCHOR,
    WIDGET_KEY_CONFLUENCE_GLOBAL,
    WIDGET_KEY_CONFLUENCE_MODE,
    WIDGET_KEY_CORE_LEVEL,
    WIDGET_KEY_DATASET_PATH,
    WIDGET_KEY_DESCRIPTION,
    WIDGET_KEY_DIRECTION_CONSTANT,
    WIDGET_KEY_DIRECTION_MODE,
    WIDGET_KEY_DIRECTION_VALUES,
    WIDGET_KEY_EMA_ADD_LENGTH,
    WIDGET_KEY_EMA_LENGTHS,
    WIDGET_KEY_EMA_TF_MODE,
    WIDGET_KEY_EMA_TIMEFRAMES,
    WIDGET_KEY_EXPLICIT_DELETE,
    WIDGET_KEY_EXPOSURE_POLICY,
    WIDGET_KEY_FLAT_BY_SESSION_CLOSE,
    WIDGET_KEY_FORMAT_PROFILE,
    WIDGET_KEY_FROM_PARTNERS,
    WIDGET_KEY_GRID_SL_VALUES,
    WIDGET_KEY_GRID_TP_VALUES,
    WIDGET_KEY_GROUP_BY,
    WIDGET_KEY_INGESTION_MODE,
    WIDGET_KEY_INSTRUMENT,
    WIDGET_KEY_INTRABAR_MODEL,
    WIDGET_KEY_LEVELS_ADVANCED,
    WIDGET_KEY_MAX_CONFLUENCES,
    WIDGET_KEY_MIN_CONFLUENCES,
    WIDGET_KEY_MIN_TRADES,
    WIDGET_KEY_MIN_VALID_CONFLUENCES,
    WIDGET_KEY_MULTIPLE_TESTING,
    WIDGET_KEY_NAKED_ONLY,
    WIDGET_KEY_NAKED_REQUIREMENT,
    WIDGET_KEY_NAME,
    WIDGET_KEY_OTF,
    WIDGET_KEY_OTF_BASELINE,
    WIDGET_KEY_OUTPUT_DIR,
    WIDGET_KEY_PIVOTS_ENABLED,
    WIDGET_KEY_PRIMARY_METRIC,
    WIDGET_KEY_PIVOT_TIMEFRAMES,
    WIDGET_KEY_POC_WINDOWS,
    WIDGET_KEY_PREV30M_ENABLED,
    WIDGET_KEY_SLIPPAGE,
    WIDGET_KEY_SMA_ADD_LENGTH,
    WIDGET_KEY_SMA_LENGTHS,
    WIDGET_KEY_SMA_TF_MODE,
    WIDGET_KEY_SMA_TIMEFRAMES,
    WIDGET_KEY_SOURCE_TIMEZONE,
    WIDGET_KEY_STAGE_MODE,
    WIDGET_KEY_STOP_LOSS,
    WIDGET_KEY_TAKE_PROFIT,
    WIDGET_KEY_TICK_PATHS,
    WIDGET_KEY_TOLERANCE_TICKS,
    WIDGET_KEY_TRIGGER,
    WIDGET_KEY_TRIGGER_TIMEFRAME,
    WIDGET_KEY_VWAP_WINDOWS,
    WIDGET_KEY_WORKERS,
    coerce_partner_levels,
    default_study_draft,
    draft_from_mapping,
    draft_to_mapping,
    draft_warnings,
    format_tick_paths_widget,
    normalize_builder_format_profile,
    normalize_tick_paths,
    parse_tick_paths_widget,
)
from thesistester.study.builder_emit import (
    emit_study_spec,
    emit_study_yaml,
    require_enabled_grid_ticks,
)
from thesistester.study.builder_hydrate import (
    hydrate_study_draft,
    hydrate_study_yaml,
    otf_preset_ids,
)
from thesistester.study.builder_widgets import (
    _partner_set_widget_key,
    _stage_include_widget_key,
    apply_grid_tick_widgets,
    apply_levels_tf_mode,
    builder_token_catalog,
    clamp_widget_selection,
    coerce_whole_number,
    collect_stage_include,
    constrain_group_by,
    declared_factor_domains,
    delete_stage_cells,
    explicit_cell_row_label,
    format_csv_values,
    format_stage_value,
    infer_stage_mode_label,
    infer_tf_mode,
    levels_advanced_enabled,
    ma_length_options,
    otf_for_selected_presets,
    otf_from_preset_ids,
    parse_csv_ints,
    parse_csv_tokens,
    preferred_group_by,
    resolve_stage_label,
    stage_mode_from_label,
)

# Used only when loader.py is stale and lacks FORMAT_PROFILE_LABELS.
# Prefer the live loader catalog so Studies and Data cannot drift at runtime.
_FORMAT_PROFILE_LABELS_FALLBACK: dict[str, str] = {
    "canonical": "Canonical / Quantower OHLCV",
    "quantower_history_exporter": "Quantower History Exporter (semicolon)",
    "ninjatrader": "NinjaTrader export",
    "sierra_intraday": "Sierra Intraday CSV",
    "databento_trades": "Databento trades CSV",
    "tick_capture": "Generic tick capture CSV",
    "second_capture": "Generic second capture CSV",
}


def bind_format_profile_labels(loader_module: Any) -> dict[str, str]:
    """Prefer ``loader.FORMAT_PROFILE_LABELS``; fall back if that name is absent.

    A bare ``from loader import FORMAT_PROFILE_LABELS`` fails the whole builder
    import when loader.py is stale. ``getattr`` keeps
    ``from builder import FORMAT_PROFILE_LABELS`` working. When the loader
    catalog exists, return that object so Studies matches the Data page.
    """
    labels = getattr(loader_module, "FORMAT_PROFILE_LABELS", None)
    if isinstance(labels, dict) and labels:
        return labels
    return dict(_FORMAT_PROFILE_LABELS_FALLBACK)


FORMAT_PROFILE_LABELS: dict[str, str] = bind_format_profile_labels(_data_loader)

# Re-export for SB2 widget rows without importing Streamlit here.
__all__ = [
    "COMMON_MA_LENGTHS",
    "DEFAULT_FORMAT_PROFILE",
    "DEFAULT_NEW_DRAFT_DATASET_PATH",
    "DEFAULT_NEW_DRAFT_FORMAT_PROFILE",
    "DEFAULT_NEW_DRAFT_INSTRUMENT",
    "DEFAULT_NEW_DRAFT_SOURCE_TIMEZONE",
    "DIRECTION_MODE_CONSTANT",
    "DIRECTION_MODE_FACTOR",
    "DIRECTION_MODE_OPTIONS",
    "MULTIPLE_TESTING_OPTIONS",
    "OTF_PRESETS",
    "OTF_PRESET_LABELS",
    "FORMAT_PROFILE_LABELS",
    "INGESTION_MODE_PRIMARY",
    "OTF_PRESET_ORDER",
    "PREFERRED_REPORT_GROUP_BY",
    "PRIMARY_METRIC_OPTIONS",
    "STAGE_MODE_EXPLICIT",
    "STAGE_MODE_FILTER",
    "STAGE_MODE_FULL",
    "STAGE_MODE_OPTIONS",
    "STUDIES_BUILDER_DRAFT_KEY",
    "STUDIES_BUILDER_PENDING_SYNC_KEY",
    "StudyDraft",
    "TF_MODE_EXPLICIT",
    "TF_MODE_NO_MA",
    "TF_MODE_OPTIONS",
    "TF_MODE_PRODUCT_DEFAULT",
    "WIDGET_KEY_BATTERY_GRID",
    "WIDGET_KEY_BATTERY_VALIDATION",
    "WIDGET_KEY_BATTERY_WALK_FORWARD",
    "WIDGET_KEY_COMMISSION",
    "WIDGET_KEY_CONFIRM_ABOVE_RUNS",
    "WIDGET_KEY_CONFLUENCE_ANCHOR",
    "WIDGET_KEY_CONFLUENCE_GLOBAL",
    "WIDGET_KEY_CONFLUENCE_MODE",
    "WIDGET_KEY_CORE_LEVEL",
    "WIDGET_KEY_DATASET_PATH",
    "WIDGET_KEY_DESCRIPTION",
    "WIDGET_KEY_DIRECTION_CONSTANT",
    "WIDGET_KEY_DIRECTION_MODE",
    "WIDGET_KEY_DIRECTION_VALUES",
    "WIDGET_KEY_EMA_ADD_LENGTH",
    "WIDGET_KEY_EMA_LENGTHS",
    "WIDGET_KEY_EMA_TF_MODE",
    "WIDGET_KEY_EMA_TIMEFRAMES",
    "WIDGET_KEY_EXPLICIT_DELETE",
    "WIDGET_KEY_EXPOSURE_POLICY",
    "WIDGET_KEY_FLAT_BY_SESSION_CLOSE",
    "WIDGET_KEY_FORMAT_PROFILE",
    "WIDGET_KEY_FROM_PARTNERS",
    "WIDGET_KEY_GRID_SL_VALUES",
    "WIDGET_KEY_GRID_TP_VALUES",
    "WIDGET_KEY_GROUP_BY",
    "WIDGET_KEY_INGESTION_MODE",
    "WIDGET_KEY_INSTRUMENT",
    "WIDGET_KEY_INTRABAR_MODEL",
    "WIDGET_KEY_LEVELS_ADVANCED",
    "WIDGET_KEY_MAX_CONFLUENCES",
    "WIDGET_KEY_MIN_CONFLUENCES",
    "WIDGET_KEY_MIN_TRADES",
    "WIDGET_KEY_MIN_VALID_CONFLUENCES",
    "WIDGET_KEY_MULTIPLE_TESTING",
    "WIDGET_KEY_NAKED_ONLY",
    "WIDGET_KEY_NAKED_REQUIREMENT",
    "WIDGET_KEY_NAME",
    "WIDGET_KEY_OTF",
    "WIDGET_KEY_OTF_BASELINE",
    "WIDGET_KEY_OUTPUT_DIR",
    "WIDGET_KEY_PIVOTS_ENABLED",
    "WIDGET_KEY_PRIMARY_METRIC",
    "WIDGET_KEY_PIVOT_TIMEFRAMES",
    "WIDGET_KEY_POC_WINDOWS",
    "WIDGET_KEY_PREV30M_ENABLED",
    "WIDGET_KEY_SLIPPAGE",
    "WIDGET_KEY_SMA_ADD_LENGTH",
    "WIDGET_KEY_SMA_LENGTHS",
    "WIDGET_KEY_SMA_TF_MODE",
    "WIDGET_KEY_SMA_TIMEFRAMES",
    "WIDGET_KEY_SOURCE_TIMEZONE",
    "WIDGET_KEY_STAGE_MODE",
    "WIDGET_KEY_STOP_LOSS",
    "WIDGET_KEY_TAKE_PROFIT",
    "WIDGET_KEY_TICK_PATHS",
    "WIDGET_KEY_TOLERANCE_TICKS",
    "WIDGET_KEY_TRIGGER",
    "WIDGET_KEY_TRIGGER_TIMEFRAME",
    "WIDGET_KEY_VWAP_WINDOWS",
    "WIDGET_KEY_WORKERS",
    "_partner_set_widget_key",
    "_stage_include_widget_key",
    "apply_grid_tick_widgets",
    "apply_levels_tf_mode",
    "bind_format_profile_labels",
    "builder_token_catalog",
    "clamp_widget_selection",
    "coerce_partner_levels",
    "coerce_whole_number",
    "collect_stage_include",
    "constrain_group_by",
    "declared_factor_domains",
    "default_study_draft",
    "delete_stage_cells",
    "draft_from_mapping",
    "draft_to_mapping",
    "draft_warnings",
    "emit_study_spec",
    "emit_study_yaml",
    "explicit_cell_row_label",
    "format_csv_values",
    "format_stage_value",
    "format_tick_paths_widget",
    "hydrate_study_draft",
    "hydrate_study_yaml",
    "infer_stage_mode_label",
    "infer_tf_mode",
    "levels_advanced_enabled",
    "ma_length_options",
    "normalize_builder_format_profile",
    "normalize_tick_paths",
    "otf_for_selected_presets",
    "otf_from_preset_ids",
    "otf_preset_ids",
    "parse_csv_ints",
    "parse_csv_tokens",
    "parse_tick_paths_widget",
    "preferred_group_by",
    "require_enabled_grid_ticks",
    "resolve_stage_label",
    "stage_mode_from_label",
]
