"""SO1–SO4 / SO7–SO9 Study Observatory façade (C-24 / QI-07-07).

Join / desk / lens / query live in sibling modules. Public names stay here.
Concatenates existing ``results_index.csv`` ⟕ ``study.expansion.json`` plus
StudySpec locks across SV1 catalog hits. SO3 attaches optional Program B
projections. SO4 persists query-only desks under the ThesisTester store.
Does not call ``report_study``, ``rollup_study``, or ``run_study``. Does not
unzip cell bundles. Does not write ``results/studies/``.

This module must not import Streamlit, Plotly, ``execute``, ``cli_study``,
``thesistester.cli``, ``launch``, ``builder``, ``promote``, ``tools``, or
``rollup``.
"""

from __future__ import annotations

from thesistester.study.observatory_desks import (
    ObservatoryDesk,
    delete_observatory_desk,
    list_observatory_desks,
    observatory_desk_from_payload,
    observatory_desk_query_state,
    observatory_desks_dir,
    parse_observatory_desk,
    save_observatory_desk,
)
from thesistester.study.observatory_join import (
    ObservatoryModel,
    dir_artifact_stamp,
    load_observatory_frame,
)
from thesistester.study.viewer import default_study_viewer_roots
from thesistester.study.observatory_lens import (
    attach_program_b_projections,
    desk_class_counts,
    desk_class_for,
    heatmap_class_z,
    heatmap_focus_label,
    heatmap_focus_pending_facets,
    is_program_b_pair_row,
    parse_heatmap_focus_label,
    partners_nonempty,
    program_b_heatmap_cells,
    resolve_program_b_lens,
    useful_confluence_for,
    wave0_study_name_for_core,
)
from thesistester.study.observatory_query import (
    apply_facets,
    cell_choice_labels,
    cohort_choice_labels,
    cohort_differ_fields,
    constrain_facet_selection,
    corpus_progress_counts,
    directional_integrity_counts,
    displayed_min_trades,
    drift_class_counts,
    format_cohort_label,
    format_heatmap_direction_count,
    format_observatory_table,
    inspect_selected_run_for_drill,
    majority_cohort_key,
    observatory_cli_frame,
    observatory_studies_table,
    parse_cohort_key,
    query_facets_for_frame,
    sort_observatory_frame,
    sort_observatory_studies,
    study_choice_labels,
    unique_facet_values,
)
from thesistester.study.observatory_support import (
    CLI_COLUMNS,
    COHORT_FIELDS,
    DESK_CLASS_ORDER,
    DESK_FACET_COLUMNS,
    DESK_LENS_MODES,
    DESK_SCHEMA_VERSION,
    DESK_STORE_DIRNAME,
    DESK_STORE_NAMESPACE,
    HEATMAP_CLASS_Z,
    HEATMAP_SOLO_PARTNER,
    HEATMAP_Z_MAX,
    HEATMAP_Z_MISSING,
    LEDGER_JSON,
    LENS_FACET_COLUMNS,
    LOCKED_FRAME_COLUMNS,
    OBSERVATORY_HONESTY,
    PROGRAM_B_LENS_PACKET_CHROME,
    SORT_ALLOW_LIST,
    STUDIES_COLUMNS,
    STUDIES_TABLE_COLUMNS,
    EXPANSION_JSON,
    ObservatoryError,
    canonical_facet_value,
    classify_drift_class,
    cohort_key_from_values,
    lens_hint_for,
    sample_class_for,
    setup_kind_for,
)

__all__ = [
    "CLI_COLUMNS",
    "COHORT_FIELDS",
    "DESK_CLASS_ORDER",
    "DESK_FACET_COLUMNS",
    "DESK_LENS_MODES",
    "DESK_SCHEMA_VERSION",
    "DESK_STORE_DIRNAME",
    "DESK_STORE_NAMESPACE",
    "EXPANSION_JSON",
    "HEATMAP_CLASS_Z",
    "HEATMAP_SOLO_PARTNER",
    "HEATMAP_Z_MAX",
    "HEATMAP_Z_MISSING",
    "LEDGER_JSON",
    "LENS_FACET_COLUMNS",
    "LOCKED_FRAME_COLUMNS",
    "OBSERVATORY_HONESTY",
    "PROGRAM_B_LENS_PACKET_CHROME",
    "SORT_ALLOW_LIST",
    "STUDIES_COLUMNS",
    "STUDIES_TABLE_COLUMNS",
    "ObservatoryDesk",
    "ObservatoryError",
    "ObservatoryModel",
    "apply_facets",
    "attach_program_b_projections",
    "canonical_facet_value",
    "cell_choice_labels",
    "classify_drift_class",
    "cohort_choice_labels",
    "cohort_differ_fields",
    "cohort_key_from_values",
    "constrain_facet_selection",
    "corpus_progress_counts",
    "default_study_viewer_roots",
    "delete_observatory_desk",
    "desk_class_counts",
    "desk_class_for",
    "dir_artifact_stamp",
    "directional_integrity_counts",
    "displayed_min_trades",
    "drift_class_counts",
    "format_cohort_label",
    "format_heatmap_direction_count",
    "format_observatory_table",
    "heatmap_class_z",
    "heatmap_focus_label",
    "heatmap_focus_pending_facets",
    "inspect_selected_run_for_drill",
    "is_program_b_pair_row",
    "lens_hint_for",
    "list_observatory_desks",
    "load_observatory_frame",
    "majority_cohort_key",
    "observatory_cli_frame",
    "observatory_desk_from_payload",
    "observatory_desk_query_state",
    "observatory_desks_dir",
    "observatory_studies_table",
    "parse_cohort_key",
    "parse_heatmap_focus_label",
    "parse_observatory_desk",
    "partners_nonempty",
    "program_b_heatmap_cells",
    "query_facets_for_frame",
    "resolve_program_b_lens",
    "sample_class_for",
    "save_observatory_desk",
    "setup_kind_for",
    "sort_observatory_frame",
    "sort_observatory_studies",
    "study_choice_labels",
    "unique_facet_values",
    "useful_confluence_for",
    "wave0_study_name_for_core",
]
