# Set THESISTESTER_STORE_DIR for a local Windows ThesisTester checkout.
# Default: <repo>\.thesistester_store  (for C:\dev\ThesisTester -> C:\dev\ThesisTester\.thesistester_store)
#
# Usage (from repo root, PowerShell):
#   .\scripts\set_store_dir.ps1
#   .\scripts\set_store_dir.ps1 -StoreDir "D:\data\thesistester_store"
#   .\scripts\set_store_dir.ps1 -UserEnv   # also write User-level permanent env var
#
# After -UserEnv, restart the terminal / IDE so Streamlit sees the new variable.

[CmdletBinding()]
param(
    [string]$StoreDir = "",
    [switch]$UserEnv
)

$ErrorActionPreference = "Stop"

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
if (-not $StoreDir) {
    $StoreDir = Join-Path $RepoRoot ".thesistester_store"
}

$StoreDir = [System.IO.Path]::GetFullPath($StoreDir)
New-Item -ItemType Directory -Force -Path $StoreDir | Out-Null

$env:THESISTESTER_STORE_DIR = $StoreDir
Write-Host "Session THESISTESTER_STORE_DIR=$StoreDir"

$DotEnvPath = Join-Path $RepoRoot ".env"
$DotEnvLine = "THESISTESTER_STORE_DIR=$StoreDir"
if (Test-Path $DotEnvPath) {
    $existing = Get-Content -LiteralPath $DotEnvPath -ErrorAction SilentlyContinue
    # Drop both KEY= and export KEY= forms so Python dotenv load cannot keep a stale value.
    $filtered = @($existing | Where-Object { $_ -notmatch '^\s*(export\s+)?THESISTESTER_STORE_DIR\s*=' })
    $filtered + $DotEnvLine | Set-Content -LiteralPath $DotEnvPath -Encoding utf8
} else {
    @(
        "# Generated by scripts/set_store_dir.ps1 — do not commit.",
        $DotEnvLine
    ) | Set-Content -LiteralPath $DotEnvPath -Encoding utf8
}
Write-Host "Wrote $DotEnvPath"

if ($UserEnv) {
    [System.Environment]::SetEnvironmentVariable(
        "THESISTESTER_STORE_DIR",
        $StoreDir,
        "User"
    )
    Write-Host "Set User environment variable THESISTESTER_STORE_DIR (restart shell/IDE to pick up)."
}

Write-Host "Done. Restart Streamlit if it is already running."
