"""Versioned contracts and capability registry for the AI Research Assistant."""

from thesistester.assistant.contracts import (
    ASSISTANT_CONTRACT_SCHEMA_VERSION,
    AssistantContractError,
    AssistantRequest,
    Capability,
    CapabilityMode,
    ConfirmationLevel,
    OrchestrationStatus,
    ResourceEnvelope,
    StructuredError,
    UnknownCapabilityError,
    structured_error,
)
from thesistester.assistant.handlers import HANDLER_REGISTRY, get_handler
from thesistester.assistant.registry import (
    FEATURE_PARITY_REGISTRY,
    get_capability,
    validate_capability_request,
)
from thesistester.assistant.repository import (
    ASSISTANT_REPOSITORY_SCHEMA_VERSION,
    AssistantRepositoryError,
    Conversation,
    InvalidStateTransitionError,
    LocalThesisRepository,
    RepositoryConflictError,
    RepositoryCorruptionError,
    RepositoryReadOnlyError,
    ResearchRun,
    SpecVersion,
    Thesis,
)
from thesistester.assistant.tools import AssistantToolError, AssistantTools, ToolLimits
from thesistester.assistant.thesis_compiler import (
    COMPILER_VERSION,
    RUN_SPEC_DRAFT_SCHEMA_VERSION,
    StructuredThesisChoices,
    ThesisDraft,
    compile_canonical_run_spec,
    map_persisted_confirmed_run_spec,
    map_thesis_choices_to_run_spec,
    compile_run_spec,
    compile_thesis,
    normalize_setup_level_selection,
    normalize_walk_forward_controls,
)
from thesistester.assistant.explainer import (
    EvidencePacket,
    build_evidence_packet,
    compare_evidence,
    explain_evidence,
)
from thesistester.assistant.orchestrator import (
    AssistantOrchestrator,
    OrchestrationResult,
    confirmed_run_feedback,
    list_payload_or_error,
)
from thesistester.assistant.comparison import COMPARISON_SCHEMA_VERSION, Comparison
from thesistester.assistant.workspace import (
    ASSISTANT_SESSION_KEYS,
    THESIS_SCOPED_STAGING_KEYS,
    active_bundle_handoff,
    build_plan_review,
    build_provenance_card,
    clear_thesis_scoped_state,
    init_assistant_session_state,
    latest_unresolved_assumptions,
    select_thesis,
)

__all__ = [
    "ASSISTANT_CONTRACT_SCHEMA_VERSION",
    "ASSISTANT_REPOSITORY_SCHEMA_VERSION",
    "AssistantContractError",
    "AssistantRepositoryError",
    "AssistantOrchestrator",
    "AssistantToolError",
    "AssistantTools",
    "AssistantRequest",
    "Capability",
    "CapabilityMode",
    "COMPILER_VERSION",
    "RUN_SPEC_DRAFT_SCHEMA_VERSION",
    "COMPARISON_SCHEMA_VERSION",
    "Comparison",
    "EvidencePacket",
    "ConfirmationLevel",
    "Conversation",
    "FEATURE_PARITY_REGISTRY",
    "HANDLER_REGISTRY",
    "InvalidStateTransitionError",
    "LocalThesisRepository",
    "OrchestrationResult",
    "OrchestrationStatus",
    "confirmed_run_feedback",
    "list_payload_or_error",
    "RepositoryConflictError",
    "RepositoryCorruptionError",
    "RepositoryReadOnlyError",
    "ResearchRun",
    "ResourceEnvelope",
    "SpecVersion",
    "StructuredError",
    "Thesis",
    "StructuredThesisChoices",
    "ThesisDraft",
    "ToolLimits",
    "UnknownCapabilityError",
    "get_capability",
    "get_handler",
    "structured_error",
    "validate_capability_request",
    "compile_thesis",
    "compile_run_spec",
    "compile_canonical_run_spec",
    "map_persisted_confirmed_run_spec",
    "map_thesis_choices_to_run_spec",
    "normalize_setup_level_selection",
    "normalize_walk_forward_controls",
    "build_evidence_packet",
    "compare_evidence",
    "explain_evidence",
    "ASSISTANT_SESSION_KEYS",
    "THESIS_SCOPED_STAGING_KEYS",
    "active_bundle_handoff",
    "build_plan_review",
    "build_provenance_card",
    "clear_thesis_scoped_state",
    "init_assistant_session_state",
    "latest_unresolved_assumptions",
    "select_thesis",
]
